# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0003_auto_20150530_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyassertion',
            options={'permissions': (('change_assertion_author', 'Can change the author of an assertion'), ('change_assertion_contributors', 'Can change contributors to an assertion'), ('change_assertion_status', 'Can change publication status'), ('change_published_items', 'Can change published items')), 'verbose_name': 'assertion'},
        ),
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.CharField(help_text='Separate multiple names with ", "', max_length=500),
        ),
        migrations.AlterField(
            model_name='date',
            name='sort_date',
            field=models.IntegerField(blank=True, help_text='Year used for sorting purposes', null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='name',
            field=models.CharField(help_text='Separate multiple names with ", "', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Separate multiple names with ", "', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='sort_date',
            field=models.IntegerField(blank=True, help_text='Year used for sorting purposes', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='name',
            field=models.CharField(help_text='Separate multiple names with ", "', max_length=500),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='source',
            name='abbreviation',
            field=models.CharField(help_text='Bibliographic reference, eg. "Nattier 1992"', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.CharField(help_text='Format: YYYY. Use the earliest date if there is a range', max_length=5),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(help_text='Full bibliographic details'),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='text',
            name='identifier',
            field=models.TextField(blank=True, help_text='A derived field holding all of the identifiers asserted for this text.'),
        ),
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Separate multiple names with ", "', max_length=500),
        ),
    ]
