# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0004_auto_20181031_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyassertion',
            name='sources',
            field=models.ManyToManyField(to='attribution.Source'),
        ),
    ]
