# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 04:17
from __future__ import unicode_literals

from django.db import migrations


def make_many_sources(apps, schema_editor):
    """Adds the Source object in PropertyAssertion.source to the
    many-to-many relationship in PropertyAssertion.sources."""
    Assertion = apps.get_model('attribution', 'PropertyAssertion')
    for assertion in Assertion.objects.all():
        assertion.sources.add(assertion.source)


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0005_propertyassertion_sources'),
    ]

    operations = [
        migrations.RunPython(make_many_sources),
    ]
