# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0006_auto_20181031_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyassertion',
            name='source',
        ),
        migrations.AlterField(
            model_name='propertyassertion',
            name='sources',
            field=models.ManyToManyField(related_name='assertions', to='attribution.Source'),
        ),
    ]
