# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0007_auto_20181031_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrole',
            name='predicate_uri',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
